"""add_ws_recommendations_and_events

Revision ID: 5f54d0b7e098
Revises: 487f8223b0b8
Create Date: 2026-05-16 20:46:39.015801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f54d0b7e098'
down_revision: Union[str, None] = '487f8223b0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ws_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('cutloss_price', sa.Float(), nullable=True),
    sa.Column('thesis', sa.String(), nullable=True),
    sa.Column('risk_note', sa.String(), nullable=True),
    sa.Column('closed_reason', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['broker_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ws_recommendations_broker_id'), 'ws_recommendations', ['broker_id'], unique=False)
    op.create_index(op.f('ix_ws_recommendations_workspace_id'), 'ws_recommendations', ['workspace_id'], unique=False)
    op.create_table('recommendation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('before_state', sa.String(), nullable=True),
    sa.Column('after_state', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ws_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_recommendation_id'), 'recommendation_events', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_recommendation_id'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_index(op.f('ix_ws_recommendations_workspace_id'), table_name='ws_recommendations')
    op.drop_index(op.f('ix_ws_recommendations_broker_id'), table_name='ws_recommendations')
    op.drop_table('ws_recommendations')
    # ### end Alembic commands ###
