"""Add missing portfolio and inquiry tables

Revision ID: fcdf6622e73a
Revises: 20260516_0001
Create Date: 2026-05-16 18:26:02.769522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcdf6622e73a'
down_revision: Union[str, None] = '20260516_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_trading',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('f_buy_val', sa.Float(), nullable=False),
    sa.Column('f_sell_val', sa.Float(), nullable=False),
    sa.Column('net_val', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'trading_date')
    )
    op.create_table('index_snapshot',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('change_point', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('breadth_green', sa.Integer(), nullable=True),
    sa.Column('breadth_red', sa.Integer(), nullable=True),
    sa.Column('breadth_yellow', sa.Integer(), nullable=True),
    sa.Column('breadth_ceiling', sa.Integer(), nullable=True),
    sa.Column('breadth_floor', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'trading_date')
    )
    op.create_table('market_prices',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ref_price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'trading_date')
    )
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('listed_shares', sa.BigInteger(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_broker', sa.UUID(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_broker'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_assigned_broker'), 'inquiries', ['assigned_broker'], unique=False)
    op.create_index(op.f('ix_inquiries_created_by'), 'inquiries', ['created_by'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('trading_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_messages_inquiry_id'), 'inquiry_messages', ['inquiry_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_portfolio_id'), 'portfolio_items', ['portfolio_id'], unique=False)
    op.alter_column('profiles', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'INVESTOR'::character varying"))
    op.drop_constraint(op.f('uq_workspace_membership_profile'), 'workspace_memberships', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_workspace_membership_profile'), 'workspace_memberships', ['workspace_id', 'profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('profiles', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'INVESTOR'::character varying"))
    op.drop_index(op.f('ix_portfolio_items_portfolio_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_inquiry_messages_inquiry_id'), table_name='inquiry_messages')
    op.drop_table('inquiry_messages')
    op.drop_table('recommendations')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inquiries_created_by'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_assigned_broker'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_table('stocks')
    op.drop_table('market_prices')
    op.drop_table('index_snapshot')
    op.drop_table('foreign_trading')
    # ### end Alembic commands ###
